# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'churchReact' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for churchReact
  pod 'Google/SignIn'

  target 'churchReact-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'churchReactTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
