# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'appReact' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  react_native_path = "../node_modules/react-native"
  pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga"

  # Pods for appReact
  pod 'Firebase/Core'
  pod 'FirebaseMessaging', '2.0.7'

  target 'appReact-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'appReactTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
