# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'churchReact' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  react_native_path = "../node_modules/react-native"
  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "React", :path => react_native_path, :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  # Pods for churchReact
  pod 'Google/SignIn'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

  target 'churchReact-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'churchReactTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
